### PR TITLE
Multi-throw buttons in vst plugin

### PR DESCRIPTION
**Pull request by Federerer**
Hi, I've added support for properly displaying/saving state of the multi throw buttons in VST plugin and also done a small cleanup 😉 There is still a room for improvement, but I didn't wanted to spend too much time on this, because I have plans to try porting UI to Avalonia for cross-platform support, but that's a topic for another issue 🙂 I've attached a new test circuit so you can test my changes.

### CODE REVIEW

**Comment by mikeoliphant** [comment]
If you submit a simple PR with just the multi-throw button support and not the MVVM refactor, I'll be happy to merge it.

**Comment by Federerer** [comment]
Well, I don't think that this will make this PR much shorter. Most of the changes are required for this to work. I can revert some pure stylistic and naming changes, and put some classes back into single file as they were, but this might reduce readability and maintainability. One thing that could be done to reduce size of this a little and also reduce code duplication would be to move implementations from MVVM folder to separate project, as they are basically the same as in LiveSPICE project or even better switching to external library for this like [this one](https://github.com/windows-toolkit/WindowsCommunityToolkit/tree/master/Microsoft.Toolkit.Mvvm) but I've been trying to avoid solution wide changes at this point so I decided to keep this PR self-contained. If you have any specific suggestions what you need me to change, feel free to comment 🙂

**Comment by mikeoliphant** [comment]
It looks like the only functional change is adding a Position property to the button controls, and exposing that as a colored button in the UI - that should be possible with few simple changes to the existing framework.

Unless I'm missing something, the new Position property doesn't seem to be hooked up into anything in the actual simulation?

**Comment by mikeoliphant** [comment]
Ignore my second comment - I see now that Position is in classes that implement the IButtonControl interface.

**Comment by mikeoliphant** [comment]
I've pushed some multi-throw support changes to a branch:

https://github.com/dsharlet/LiveSPICE/tree/multithrow

I added a separate template for handling multi-throw switches using a combo box. This preserves the existing "power button" switch for the more common two-position switches. The Multi-throw XAML hard-codes 3 positions, since this seems to be all that is currently used. It likely would not be hard to generalize to arbitrary numbers of positions if necessary.

I tested it with your sample schematic, and it seems to work - can you give it a try and let me know if it works for you?

Thanks.

**Comment by Federerer** [comment]
Grouping doesn't work on your branch, but that should be easy to fix.  I don't particularly like combo boxes for that purpose, but this is probably only solution if you want to avoid using `INotifyPropertyChanged` at all cost. Is there any technical reason why you don't wanna go mvvm way? You are already partially using it without knowing using your 'Wrapper' components 😉

Just two notes, cause I can't comment on your branch:
1. `Binding RelativeSource={RelativeSource Self}, Path=DataContext` is equivalent to just `Binding`.
2. You don't need to do all that magic with setters and `OjbectTypeConverter` check how it's implemented on my branch.

**Comment by mikeoliphant** [comment]
Just seems unnecessary. As is using INotifyPropertyChanged, since values only propagate from UI->simulation.

**Comment by mikeoliphant** [comment]
I have merged my multi-throw branch, so I am going to go ahead and close this PR.

**Pull request closed without merging**
