### PR TITLE
Github actions for builds and releases

### PR DESCRIPTION
**Pull request by mdouchement**
This PR addresses the issue #172:
- Example of test: https://github.com/mdouchement/LiveSPICE/actions/runs/4747535761
- Example of snapshot: https://github.com/mdouchement/LiveSPICE/actions/runs/4747537811
- Example of release: https://github.com/mdouchement/LiveSPICE/releases/tag/v0.14-testouille
  - The action is trigged when a new release is created in Github

~~VST part is omitted/disabled due to my lack of .NET knowledge but it can be fixed in another PR by someone else.~~

### CODE REVIEW

**Comment by mikeoliphant** [comment]
> VST part is omitted/disabled due to my lack of .NET knowledge but it can be fixed in another PR by someone else.

I think the VST gets installed by the installer.

**Comment by erikgitarristen** [comment]
The vst does not install while using this installer. Could it be possible to update the vst to read the files from the latest liveSPICE? It seems that the vst can't cope with the new electrical components in the latest liveSPICE, or am i doing something wrong?

**Comment by mikeoliphant** [comment]
> > VST part is omitted/disabled due to my lack of .NET knowledge but it can be fixed in another PR by someone else.
> 
> I think the VST gets installed by the installer.

Ah - just noticed that you commented it out of the installer config. I'll have a look at it.

**Comment by mikeoliphant** [comment]
@mdouchement Just change "net5.0-windows" to "net6.0-windows" in the VST install lines, and it should work.

**Comment by mikeoliphant** [comment]
Looks good!

@dsharlet any objections to merging?

**Comment by dsharlet** [comment]
This looks great, thank you for doing this, and @mikeoliphant for the review and VST support!

**Pull request merged**
