### PR TITLE
Enable running release manually

### PR DESCRIPTION
**Pull request by dsharlet**
Embarrassingly, I can't figure out how to run the release workflow. I think it might run automatically when I make a release... but I'm not sure? I wanted to test the release before making it, so I'd rather have a way to run it manually too.

Trying to address #172.

### CODE REVIEW

**Comment by dsharlet** [comment]
Post merge commentary: this seems to have worked, I now can run the workflow manually :)

**Comment by mdouchement** [comment]
Hello, you just have to go in the [GH release pane](https://github.com/dsharlet/LiveSPICE/releases) and create a new release associated to a tag, that will trigger the release.yml workflow and it will appends assets to the created release.

**Comment by dsharlet** [comment]
I figured as much, however, I wanted to test the installer + usage of it before actually making the release, and I wanted to test the actual output of the workflow.

**Comment by dsharlet** [comment]
This doesn't actually work when run manually. I think I'm going to give up on my testing strategy. I'm going to test locally first, make the release, then spot test that release installer to make sure it's not different somehow. I wouldn't expect any subtle changes to occur there, so that second test just needs to be a spot check I think.

**Pull request merged**
